name = "SparsePFT"
uuid = "18e17681-6372-40f0-8608-05261a8be169"
authors = ["WhiffleFish <tylertronics@gmail.com>"]
version = "0.1.0"

[deps]
MCTS = "e12ccd36-dcad-5f33-8774-9175229e7b33"
POMDPModelTools = "08074719-1b2a-587c-a292-00f91cc44415"
POMDPs = "a93abf59-7444-517b-a68a-c42f96afdd7d"
ParticleFilters = "c8b314e2-9260-5cf8-ae76-3be7461ca6d0"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
ParticleFilters = "0.5"
POMDPModelTools = "0.3"
MCTS = "0.5"
POMDPs = "0.9"
julia = "1.7"